CREATE SCHEMA Other;

GO

CREATE TABLE Other.SchemaOther 
(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	Name NVARCHAR(MAX) NOT NULL,
)

GO

CREATE TABLE CompositeKeys
(
	Key1 INT NOT NULL,
	Key2 INT NOT NULL,
	PRIMARY KEY (Key1, Key2)
);

CREATE TABLE KeyAlias
(
	[Key] INT NOT NULL IDENTITY PRIMARY KEY,
	Name NVARCHAR(MAX) NOT NULL
);

CREATE TABLE KeyInt32
(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	Name NVARCHAR(MAX) NOT NULL
);

CREATE TABLE KeyInt64
(
	Id BIGINT NOT NULL IDENTITY PRIMARY KEY,
	Name NVARCHAR(MAX) NOT NULL
);

CREATE TABLE KeyString
(
	Name NVARCHAR(200) PRIMARY KEY,
	Age INT NOT NULL
);

CREATE TABLE NoAutoIdentity
(
	Id INT NOT NULL PRIMARY KEY,
	Name NVARCHAR(MAX) NOT NULL
);

CREATE TABLE NoKey
(
	Name NVARCHAR(MAX) NOT NULL,
	Age INT NOT NULL
);

CREATE TABLE PropertyEnum
(
	Id INT NOT NULL PRIMARY KEY,
	FavoriteColor INT NULL
);

CREATE TABLE Users
(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	Name NVARCHAR(MAX) NOT NULL,
	Age INT NOT NULL
);