// <copyright file="ColumnSchema.cs" company="Berkeleybross">
// Copyright (c) Berkeleybross. All rights reserved.
// </copyright>
namespace Dapper.MicroCRUD.Entities
{
    /// <summary>
    /// Represents a column in a <see cref="TableSchema"/>.
    /// </summary>
    public class ColumnSchema
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ColumnSchema"/> class.
        /// </summary>
        public ColumnSchema(string columnName, string propertyName, bool isPrimaryKey, bool isGeneratedByDatabase)
        {
            this.ColumnName = columnName;
            this.PropertyName = propertyName;
            this.IsPrimaryKey = isPrimaryKey;
            this.IsGeneratedByDatabase = isGeneratedByDatabase;
        }

        /// <summary>
        /// Gets the name of the column in the database
        /// </summary>
        public string ColumnName { get; }

        /// <summary>
        /// Gets the name of the original entity property.
        /// </summary>
        public string PropertyName { get; }

        /// <summary>
        /// Gets a value indicating whether this column is the primary key of its table.
        /// </summary>
        public bool IsPrimaryKey { get; }

        /// <summary>
        /// Gets a value indicating whether this column is generated by the database, and shouldn't be used in insert statements.
        /// </summary>
        public bool IsGeneratedByDatabase { get; }
    }
}